# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carl Shapiro
email: carl@shapiro.cc
description: > # this means to ignore newlines until "baseurl:"
 Carl Shapiro is a postdoctoral fellow at Johns Hopkins University.
url: "http://carl.shapiro.cc" # the base hostname & protocol for your site
github_username: crshapiro
scholar_username: V4POEocAAAAJ
address: 323 Latrobe Hall
address2: Johns Hopkins University
address3: 3400 N. Charles St.
city: Baltimore
state: MD
zip: 21218

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

# Google Analytics
google_analytics: UA-115369337-1
